### ISSUE TITLE
Dont Repeat Yourself or DRY method

### ISSUE THREAD

**Issue by tommygebru** [SebaMG/prj-rev-bwfs-dasmoto#6]
Consider applying css styles to the html elements once, instead of having to write out the font-family tags towards your html document multiple times.

The font-family could be assigned to the entire page with the html or body tags. 

This applies to the font-weight style too

**Comment by SebaMG** [comment]
Thanks that makes sense! I think I gotta plan my stylesheet instead of just start to type what I see.
